services:
  control-project:
    build:
      context: .
      dockerfile: Dockerfile
    image: control-project:1.0
    container_name: control-project
    ports:
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
    restart: unless-stopped
