spring.application.name=Control Project
spring.main.banner-mode=off

app.bridge.bi-tcp-port=3001
app.bridge.uni-tcp-port=3002
app.bridge.bi-web-socket-port=3003
app.bridge.uni-web-socket-port=3004
app.bridge.max-frame-length=131072
app.bridge.web-socket-path=/
